import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const roboto_init = Roboto ({
  subsets: ['latin'],
  weight: ['100', '300','700'],
  variable: '--font-roboto',
})

export const metadata = {
  title: "Ed - Street Fighter 6",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_init.variable}>{children}</body>
    </html>
  );
}
